### ISSUE TITLE
Hi, may I ask how to install your project?

### ISSUE THREAD

**Issue by yuhui-xie** [SLAMWang/fasterGICP#3]
Your installation step:

git clone https://github.com/SMRT-AIST/fast_gicp --recursive
mkdir fast_gicp/build && cd fast_gicp/build
cmake .. -DCMAKE_BUILD_TYPE=Release
# enable cuda-based implementations
# cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_VGICP_CUDA=ON
make -j8

seems not match this project.
The projected used is fast_gicp;

**Comment by SLAMWang** [comment]
Yes, in this project, cuda is not used, most modifications are performed in fast_gicp_impl.hpp.
Our project is based on fast_gicp.
